server:
  port: 5555
  
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://eurekanode0:8761/eureka/

#  debug:
#    request: true
#
zuul:
    sensitiveHeaders: Cookie,Set-Cookie
    
signing:
    key: "345345fsdfsf5345"
