apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: celery-worker
        image: 127.0.0.1:5000/django:latest
        command: ['celery', '-A', 'mysite', 'worker', '-l', 'debug']
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_HOST
          value: redis-service
#        - name: POSTGRES_USER
#          valueFrom:
#            secretKeyRef:
#              name: postgres-secret
#              key: database-user
#        - name: POSTGRES_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: postgres-secret
#              key: database-password