apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJsb2NhbGhvc3Q6NTAwMCI6eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwicGFzc3dvcmQiOiJ0ZXN0cGFzc3dvcmQiLCJhdXRoIjoiZEdWemRIVnpaWEk2ZEdWemRIQmhjM04zYjNKayJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2021-05-15T06:34:09Z"
  name: regcred
  namespace: default
  resourceVersion: "463185"
  uid: ceaea348-0337-49de-ba5f-102e058d4bfb
type: kubernetes.io/dockerconfigjson

#kubectl create secret docker-registry regcred --docker-server=127.0.0.1:5000 --docker-username=testuser --docker-password=testpassword 