apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: 'eureka'
  # n instances
  replicas: 3
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: eureka
        image: 127.0.0.1:5000/eureka:0.1.0
        ports:
        - containerPort: 8761
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1200Mi"
            cpu: "500m"
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
        livenessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-np
  labels:
    app: eureka
spec:
  type: NodePort
  ports:
  - port: 8761
    nodePort: 30030
    name: eureka
  selector:
    app: eureka

